---
- name: Prepare folder for docker compose
  file:
    path: "/home/{{ deploy_user }}/{{ project_folder }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0755'

- name: Find old image
  raw: "cd /home/{{ deploy_user }}/{{ project_folder }}/ && docker compose images | grep {{ project_folder }}-app | awk '{print $4}'"
  register: old_image

- debug:
    var: old_image.stdout | trim

- name: Check that the .env.example exists
  stat:
    path: "../.env.example"
  delegate_to: localhost  
  register: check_env_example

- name: Load data
  slurp:
    src: "../.env.example"
  delegate_to: localhost
  register: slurped_user_data
  when: check_env_example.stat.exists

- set_fact:
    msg: "{{ slurped_user_data.content | b64decode | regex_findall('(^[A-Z_]+)=.*$', '\\1') }}"
  register: paramlist
  when: check_env_example.stat.exists

- name: Template template env
  template: 
    src: .env.j2
    dest: .env.j2
  delegate_to: localhost
  when: check_env_example.stat.exists 

- name: Template files
  template: 
    src: "../../{{ item }}"
    dest: "/home/{{ deploy_user }}/{{ project_folder }}/{{ item.split('.j2')[0] }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0664'
  loop:
    "{{ templete_list }}"

- name: docker login
  raw: docker login profmalina.cr.cloud.ru -u "{{ dockeruser }}" -p "{{ dockerpasswd }}"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "/home/{{ deploy_user }}/{{ project_folder }}"
    pull: missing
  register: output

- name: Show results
  debug:
    var: output

- name: Prune images
  raw: "docker rmi {{ old_image.stdout | trim }}"
  ignore_errors: true
  no_log: True
